prac/homepage/urls.py
from django.conf.urls import url
from . import views

app_name = 'homepage'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajax-response-markers/$', views.return_response_markers,
        name='return_response_markers'),
    url(r'^ajax-response-infowindow/$', views.return_response_infowindow,
        name='return_response_infowindow'),
    url(r'^ajax-response-stats/$', views.return_response_stats,
        name='return_response_stats'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^privacy-cookies$', views.legal, name='legal'),
    url(r'^our-data$', views.data, name='data'),
    url(r'^ajax-post-error/', views.write_error, name='write_error')
]

prac/prac/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('homepage.urls', namespace="homepage")),
    url(r'^reporter/', include('reporter.urls', namespace='reporter')),
    url(r'^hp-predictor/', include('predictor.urls', namespace='predictor')),
    url(r'^risk/', include('riskdb.urls', namespace='riskdb')),
    url(r'^table/', include('tableview.urls', namespace='tableview'))
]

prac/homepage/models.py
from django.db import models

# Create your models here.

prac/homepage/forms.py
from django import forms

# Creates search form
class SearchForm(forms.Form):
    address = forms.CharField(label='address',
    max_length=100,
    widget=forms.TextInput(attrs={'placeholder': 'Search for an address...'}))

prac/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from .forms import SearchForm
from prac.models import Sale, Housing, CSORef, SexAgeMarriage, ReportedErrors
import googlemaps
from django.core.serializers import serialize
import math
import numpy as np
import pandas as pd
from django.db.models import Avg, Max, Min, Count
import json
from datetime import datetime
import calendar
from sklearn.cluster import KMeans


def geolocate(address_string):
    """
    Take address from search bar and return lat & long location if possible.
    :param address_string:
    :return: location, status

    Shorthand for status:
    0 - No search conducted
    1 - Good search results
    2 - Bad / No results
    """
    gmaps = googlemaps.Client(key='AIzaSyBFwN-7_erzpXeWWFe3DwMqSPKGoCjj1Hg')

    # Add Ireland to search string to remove ambiguity
    address = address_string + ' Ireland'

    # Get results from gmaps API
    geocode_result = gmaps.geocode(address)

    # If a result is returned
    if len(geocode_result) > 0:
        # Set the location as the result
        location = geocode_result[0]['geometry']['location']
        # Set map bounds
        location['l'] = location['lng'] - 0.04866600036624025
        location['r'] = location['lng'] + 0.04866600036624025
        location['t'] = location['lat'] + 0.019106276426853697
        location['b'] = location['lat'] - 0.019106276426853697
        status = 1
    else:
        status = 2

    # Check if location is within east/west boundary of Ireland
    if status is 1:
        if location['lng'] > -10.738539 and location['lng'] < -5.930445:
            pass
        else:
            status = 2

    # Check if location is within north/south boundary of Ireland
    if status is 1:
        if location['lat'] > 51.387652 and location['lat'] < 55.445918:
            pass
        else:
            status = 2

    # If a bad result, set default location
    if status is 2:
        location = {'lng': -6.2603, 'lat': 53.3498, 'l': -6.30896600036624,
                    'r': -6.211633999633818, 't': 53.368906276426856,
                    'b': 53.330685156427386}

    return location, status


def index(request):
    # Initialize form
    form = SearchForm()

    # Set default location - Central Dublin
    location = {'lng': -6.2603, 'lat': 53.3498, 'l': -6.30896600036624,
                'r': -6.211633999633818, 't': 53.368906276426856,
                'b': 53.330685156427386}
    status = 0

    # Get time of last RPPR update
    with open(settings.BASE_DIR + '/homepage' + settings.STATIC_URL +
              'RRP_timestamp.txt', 'r') as file:
        lu = file.read()

    # If refreshing after search
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            # Get address from search and geolocate
            search_address = form.cleaned_data['address']
            location, status = geolocate(search_address)

    # Filter by map boundaries
    database_list = Sale.objects.filter(quality='good',
                                        latitude__gte=location['b'],
                                        latitude__lte=location['t'],
                                        longitude__gte=location['l'],
                                        longitude__lte=location['r'])

    # Calculate maximum sale price in returned results
    datalist = Sale.objects.aggregate(Max('price'))
    max_price = datalist['price__max']

    scatter_data = {'date': [], 'price': []}
    hist_data = []

    # Loop through returned results
    for sale in database_list:
        scatter_data['date'].append(sale.sale_date)
        scatter_data['price'].append(float(sale.price))
        hist_data.append(float(sale.price))

    # Create data frame from scatter data
    df = pd.DataFrame(scatter_data, columns=['price'],
                      index=scatter_data['date'])
    df.index.names = ['date']

    df = df.set_index(pd.DatetimeIndex(df.index))
    # Group data frame sales to a weekly average
    df = df.resample('W').mean().dropna(axis=0, how='any')

    # Generate scatterplot data with correct timestamps
    scatter_data = list(map(lambda x, y:
                            [calendar.timegm(
                                x.to_pydatetime().timetuple()) * 1000,
                             round(float(y), 2)],
                            df.index.tolist(), df.values))

    # Compress histogram data by pre-binning to reduce data transfer
    compressed_hist_data = {}
    k = 0
    for v in range(25000, 5000000, 25000):
        count = 0
        for i in hist_data:
            if i > k and i <= v:
                count += 1

        if count != 0:
            compressed_hist_data[v - 12500] = count

        k = v

    # Generate 3rd order polynomial line of best fit and store
    # coefficients in a list
    lobf_coef = [float(i) for i in list(np.polyfit(
        [i[0] for i in scatter_data], [i[1] for i in scatter_data], deg=3))]

    context = {'form': form, 'latitude': location['lat'],
               'longitude': location['lng'], 'status': status,
               'database_list': database_list,
               'hist_data': compressed_hist_data,
               'scatter_data': scatter_data,
               'last_update': lu,
               'max_price': max_price, 'lobf_coef': lobf_coef}

    return render(request, 'homepage/index.html', context)


def contact(request):
    return render(request, 'homepage/contact.html')


def legal(request):
    return render(request, 'homepage/privacy-cookies.html')


def data(request):
    return render(request, 'homepage/our-data.html')


def return_response_markers(request):
    # Responds to AJAX request to display markers on map

    # Get map boundaries from request
    top = request.GET['top']
    bottom = request.GET['bottom']
    right = request.GET['right']
    left = request.GET['left']

    # Filter database by map boundaries
    database_list = Sale.objects.filter(quality='good', latitude__gte=bottom,
                                        latitude__lte=top,
                                        longitude__gte=left,
                                        longitude__lte=right)

    # If current zoom is above 13, or there are less than 2000 sales after
    # geographic filtering, do not cluster data:
    if int(request.GET['zoom']) > 13 or len(database_list) < 2000:

        b = calendar.timegm(
            datetime.strptime('2010-01-01', '%Y-%m-%d').timetuple())

        result = serialize('json', database_list,
                           fields=('uid', 'latitude', 'longitude',
                                   'price', 'sale_date'))

        # Standardizes time stamps with 01-01-2010 as 0, in order to be
        # interpreted by color scale in Javascript
        res = json.loads(result)
        for i in range(len(res)):
            t = calendar.timegm(datetime.strptime(
                res[i]['fields']['sale_date'][:10], '%Y-%m-%d').timetuple())
            res[i]['fields']['sale_date'] = str(t - b)

        return HttpResponse(json.dumps(res))

    cluster_data = {'lat': [], 'lng': []}

    # Iterate through returned results and build clustering dictionary
    for point in database_list:
        cluster_data['lat'].append(point.latitude)
        cluster_data['lng'].append(point.longitude)

    # Create data frame from clustering dictionary
    df = pd.DataFrame(cluster_data, columns=['lat', 'lng'], index=None)

    # Create and cluster data properties into 40 clusters on lat/long
    kmeans = KMeans(n_clusters=40, n_init=1, max_iter=30, tol=0.001,
                    n_jobs=2).fit(df)
    samples = kmeans.predict(df)

    centroids = kmeans.cluster_centers_

    # Return data in format: [[centroid_lat, centroid_long,
    # number in centroid], ...]
    response_data = []
    for i in range(len(centroids)):
        response_data.append([centroids[i][0], centroids[i][1],
                              len([j for j in samples if j == i])])

    response = {'data': response_data, 'cluster': 'true'}

    return HttpResponse(json.dumps(response))


def return_response_infowindow(request):
    # Returns specific information on a property when requested

    uid = request.GET['uid']

    database_list = Sale.objects.filter(uid=uid)

    result = serialize('json', database_list,
                       fields=('uid', 'sale_date', 'address', 'postcode',
                               'county', 'nfma', 'vat_ex', 'DoP', 'PSD',
                               'price'))

    return HttpResponse(result)


def latlng(clat, clng, d, dir):
    # Based on a centroid location, returns the lat/long location of a point
    # d km away in a specific direction

    R = 6378.1  # Radius of the earth

    # Sets direction in radians
    if dir == 'N':
        brng = 0
    elif dir == 'E':
        brng = 1.57
    elif dir == 'S':
        brng = 3.14
    elif dir == 'W':
        brng = 4.71
    else:
        brng = 0

    # Convert lat/long into radians
    lat1 = (clat / 180) * math.pi
    lng1 = (clng / 180) * math.pi

    # Calculate new lat/long
    lat2 = math.asin(math.sin(lat1) * math.cos(d / R) + math.cos(lat1)
                     * math.sin(d / R) * math.cos(brng))
    lng2 = lng1 + math.atan2(math.sin(brng) * math.sin(d / R) * math
                             .cos(lat1),
                             math.cos(d / R) - math.sin(lat1) * math
                             .sin(lat2))

    # returns new lat/long in degrees
    return [lat2 * (180 / math.pi), lng2 * (180 / math.pi)]


def distance(lat1, lon1, lat2, lon2):
    # Calculates the distance between two points

    p = 0.017453292519943295
    a = 0.5 - math.cos((lat2 - lat1) * p) / 2 + \
        math.cos(lat1 * p) * math.cos(lat2 * p) * \
        (1 - math.cos((lon2 - lon1) * p)) / 2

    return 12742 * math.asin(math.sqrt(a))


def retrieve_stats(queryset):

prac/homepage/templates/homepage/contact.html
{% extends 'homepage/header.html' %}

{% block content %}
    {% load staticfiles %}
    <link href="{% static 'homepage/css/contact-style.css' %}" rel="stylesheet">

    <div id="contact">
        <h2>Contact:</h2>

        <div class="person">
            <h4>Peter Adam:</h4>
            <p>E-mail: <a href="mailto:peter.adam@ucdconnect.ie">peter.adam@ucdconnect.ie</a></p>
            <p>Twitter: <a href="https://twitter.com/padams02">@Padams02</a></p>
            <p>LinkedIn: <a href="https://www.linkedin.com/in/peteradam02/">peteradam02</a></p>
            <p>Blog: <a href="https://medium.com/@padam0/">medium.com/@padam0/</a></p>
        </div>

        <div class="person">
            <h4>Andy McSweeney:</h4>
            <p>E-mail: <a href="mailto:andy.mcsweeney@ucdconnect.ie">andy.mcsweeney@ucdconnect.ie</a></p>
            <p>Twitter: <a href="https://twitter.com/Mcsweena">@Mcsweena</a></p>
            <p>LinkedIn: <a href="https://www.linkedin.com/in/mcsweeneyandy/">mcsweeneyandy</a></p>
        </div>
    </div>

{% endblock %}

prac/homepage/templates/homepage/header.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="ROBOTS" content="INDEX, FOLLOW">
        <meta name="description" content="Explore Irish property and residential house prices.">

        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:title" content="IPPE: Explore and understand your housing market!">
        <meta name="twitter:site" content="@padams02">
        <meta name="twitter:description" content="Your gateway to understanding the Irish housing market with easy to use maps use maps, graphs and stats.">
        <meta name="og:url" content="ippe.ie">
        <meta name="og:title" content="IPPE: Explore and understand your housing market!">
        <meta name="og:description" content="Your gateway to understanding the Irish housing market with easy to use maps, graphs and stats.">

        <title>Irish Property Price Explorer</title>

        <link href='https://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'/>
        <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type='text/css'/>

        {% load staticfiles %}
        <meta name="twitter:image" content="{% static 'homepage/media/social.png' %}">
        <meta name="og:image" content="{% static 'homepage/media/social.png' %}">

        <link rel="icon" href="{% static 'homepage/media/favicon.ico' %}" />
        <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'homepage/css/header-style.css' %}"  rel="stylesheet">
        <link href="{% static 'homepage/css/nouislider.min.css' %}" rel="stylesheet">
        <link href="{% static 'homepage/css/qtip.min.css' %}" rel="stylesheet">
        <link href="{% static 'predictor/css/polyfill.css' %}" rel="stylesheet">
        <script src="https://use.fontawesome.com/d4ab8b5599.js"></script>
        <script src="{% static 'homepage/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'homepage/js/d3.min.js' %}"></script>
        <script src="{% static 'homepage/js/nouislider.min.js' %}"></script>
        <script src="{% static 'homepage/js/qtip.min.js' %}"></script>
        <script src="{% static 'homepage/js/js.cookie.js' %}"></script>
        <script src="{% static 'homepage/js/header.js' %}"></script>


    </head>
    <body>
        <div id="header">
            <div class="header-col" id="h-left">
                <div class="header-row" id="oh-blue"></div>
                <div class="header-row" id="oh-green"></div>
            </div>
            <div class="header-col" id="h-mid">
                <div class="header-row" id="h-blue">
                    <a href="/" id="header-link"><div id="subhead-left">
                        <h1 id="apptitle">I<span class="title-small">RISH</span> P<span class="title-small">ROPERTY</span> P<span class="title-small">RICE</span> E<span class="title-small">XPLORER</span></h1>
                        <p>Your gateway to the Irish property market</p>
                    </div></a>
                    <div id="subhead-right">
                        <p id="ipw">In partnership with:</p>
                        <a href="https://aib.ie/">
                            <img src="{% static 'homepage/media/aib-logo-two.jpeg' %}"
                                 id="AIB-img">
                        </a>
                    </div>
                </div>
                <div class="header-row" id="h-green"></div>
            </div>
            <div class="header-col" id="h-right">
                <div class="header-row" id="oh-blue"></div>
                <div class="header-row" id="oh-green"></div>
            </div>

        </div>
        <main>
            {% block content %}
            {% endblock %}
        </main>
        <div id="footer">
            <a href="/">
                <p>Property Price Explorer</p>
            </a>
            <div class="fsep">|</div>
            <a href="{% url 'tableview:index' %}">
                <p>View Properties</p>
            </a>
            <div class="fsep">|</div>
            <a href="{% url 'reporter:index' %}">
                <p>Demographic & Price History Reports</p>
            </a>
            <div class="fsep">|</div>
            <a href="{% url 'predictor:index' %}">
                <p>House Price Prediction</p>
            </a>
            <div class="fsep">|</div>
            <a href="{% url 'riskdb:index' %}">
                <p>Mortgage Risk Dashboard</p>
            </a>
            <div class="fsep">|</div>
            <a href="/our-data">
                <p>Our Data</p>
            </a>
            <div class="fsep">|</div>
            <a href="/privacy-cookies">
                <p>Privacy & Data Collection</p>
            </a>
            <div class="fsep">|</div>
            <a href="/contact">
                <p>Contact</p>
            </a>
        </div>
        <div id="qtip-growl-container">

        </div>
    </body>
    <script src="{% static 'predictor/js/datalist.polyfill.min.js' %}"></script>
</html>

prac/homepage/templates/homepage/index.html
{% extends 'homepage/header.html' %}

{% block content %}
    {% load staticfiles %}
    <link href="{% static 'homepage/css/index-style.css' %}" rel="stylesheet">
    <script src="{% static 'homepage/js/index.js' %}"></script>

    <div class="main-col" id="m-left">
        <div class="left-content" id="search">
            {% include 'homepage/includes/search-snippet.html' %}
            {% block search %}
            {% endblock %}
        </div>
        <div class="left-content" id="map">
            {% include 'homepage/includes/map-snippet.html' %}
            {% block map %}
            {% endblock %}
            <hr>
        </div>
        <div class="left-content" id="graphs">
            {% include 'homepage/includes/graphs-snippet.html' %}
            {% block graphs %}
            {% endblock %}
        </div>
    </div>
    <div class="main-col" id="m-right">
        <div class="right-content" id="analytics-header">
            <hr id="aanaly">
            <h3>Analytics</h3>
        </div>
        <div class="right-content" id="analytics">
            <hr id="banaly">
            {% include 'homepage/includes/analytics-snippet.html' %}
            {% block analytics %}
            {% endblock %}
            <hr>
        </div>
        <div class="right-content" id="analytics-more">
            {% include 'homepage/includes/more-snippet.html' %}
            {% block more %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

prac/homepage/templates/homepage/our-data.html
{% extends 'homepage/header.html' %}

{% block content %}
    {% load staticfiles %}
    <link href="{% static 'homepage/css/data-style.css' %}" rel="stylesheet">

    <div id="data">
        <h2>Our Data</h2>

        <div class="section">
            <h4>Property Price Data</h4>
            <p>All data used and featured on <a href="/">ippe.com</a> is public
                and is taken from the <a href="https://www.propertypriceregister.ie/website/npsra/pprweb.nsf/page/ppr-home-en">Irish Residential Property Price Register</a> (RRPR).
            </p>
            <p>RPPR Data is updated approximately every two weeks, and is featured on this site the day after being made public.</p>
            <hr>
            <p>The Property Services Regulatory Authority (RPSA) who maintain the RPPR state the following:</p>
            <p class="quote">"The PSRA does not in any way edit the data. It simply publishes, in a fully transparent manner, that which is filed."</p>
            <p><a href="/">ippe.com</a> does undertake data cleaning in order to provide a clearer picture of the Irish property market. Data cleaning steps include:</p>
            <ul>
                <li>Removing all property sales marked as not at market price;</li>
                <li>Removing commerical development sales and bulk sales of apartment blocks grouped in one transaction;</li>
                <li>Removing duplicate (or near duplicate, indicators of typos) entries within a 1 month period;</li>
                <li>Removing outliers where a property is sold for less than 2 standard deviations below the average price in an Electoral District; and</li>
                <li>Removing outliers where a property is sold for more than 2 standard deviations above the average price in an Electoral District on a case
                by case basis, where no evidence of house existance and a justification of the price can be found.</li>
            </ul>
            <p>At present, the RPPR contains over 250,000 property sale records, and while the above techniques cannot claim to remove all erroneous data, we believe it's a start
            and provides a more accurate representation than the RPPR does alone. If you identify any potentially erroneous property information while using this site, please
                <a href="/contact">contact us</a> or submit a bad data report by clicking on the property on the homepage and following the link.</p>
            <p>All bad data reports submitted to us are reviewed approximately monthly and changes applied upon review.</p>
        </div>

        <div class="section">
            <h4>Property Price Predictions</h4>
            <p>All predictions made by the site are just that, predictions. The quality of any predictions made is directly influenced by the data quality of the RPPR.
            Despite the above warning from the PSRA, the data quality is generally ok, and we do our best to improve it. Regardless, we acknowledge our
            models are far from perfect, which is why we publish our margins of error, and encourage you to place all information available on this site in context.</p>
            <p>Furthermore, predictions should be considered less as Property Price predictions, and more as Property Price Register predictions. That is,
            the 'predicted' price is that which is predicted to appear on the RPPR if the house was sold. As such, for new houses, that includes VAT, but for all other
            properties it does not include tax.</p>
        </div>

        <div class="section">
            <h4>Risk Factors</h4>
            <p>Risk factors are all indicative, and all depend heavily on the specifics of the locale. Hover over the risk buttons for a more
                in-depth explanation of how risks are defined and potential pitfalls in the analysis techniques.</p>
        </div>

        <div class="section">
            <h4>Demographic</h4>
            <p>All demographic area comes from the CSO Small Area Statistics as part of the 2011 and 2016 Irish census. This information is available here:</p>
            <ul>
                <li><a href="http://www.cso.ie/en/census/census2011smallareapopulationstatisticssaps/">2011</a></li>
                <li><a href="http://www.cso.ie/en/census/census2016reports/census2016smallareapopulationstatistics/">2016</a></li>
            </ul>
            <p>Statistics are mapped to Electoral Districts, the border coordinates are taken from <a href="https://www.townlands.ie/">townlands.ie</a>.
                There are some situations where Electoral District names differ between the CSO and townlands.ie,
                and hence geographic and demographic information may be misaligned.</p>
        </div>

{% endblock %}